name: Database Migration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

jobs:
  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Supabase CLI
        run: |
          npm install -g supabase

      - name: Run database migrations
        run: |
          supabase db push --project-ref ${{ env.SUPABASE_URL }} --db-url ${{ secrets.DATABASE_URL }}

      - name: Verify migration
        run: |
          echo "Verifying database schema..."
          # Add verification commands here

  backup:
    name: Backup Database
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          npm install -g supabase

      - name: Create database backup
        run: |
          supabase db dump --project-ref ${{ env.SUPABASE_URL }} --file backup-$(date +%Y%m%d-%H%M%S).sql

      - name: Upload backup to storage
        run: |
          echo "Uploading backup to storage..."
          # Add backup upload logic here